### ISSUE TITLE
Moving repo to bbc org

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#100]
Email from David lists a few things that will need to happen for this to be done:

> Hi,
> 
> Finally had a chance to finish working through this. There are a few niggles to resolve before we move this over:
> 
> 1) Change license copyright notice over to BBC
> 
> 2) Remove the colorize gem dependency — (we’ve got a license clash MIT/GPL)
> 
> 3) Remove usage of circle-ci (I’m waiting for feedback from infosec & legal on whether we can use circle)
> 
> Once done, we can this move it to the bbc org, and I’ll add Josh etc in as external collaborators. Plus I’ll need adding as a gem owner.
> 
> Thanks,
> David

**Comment by mattwynne** [comment]
OK @davidbuckhurst I think we're ready to roll. I've added you as a gem owner under your @bbc.co.uk email - which seems to be [this user](https://rubygems.org/profiles/bbc) - OK?

Can you check everything else is in order, then let me know and I can move it over.

**Comment by joshski** [comment]
This is done, we are here!
