### ISSUE TITLE
Strategy for integrating bbc-a11y standards into HTML_CodeSniffer

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#103]
Options:
1. use a fork
2. @joshski talk to squizlabs and ask if they'll want to integrate the BBC standards into their codebase
3. @joshski talk to squizlabs to see if they'll build in an extension point that makes it easier to plug in new standards.

**Comment by EmmaJP** [comment]
@joshski I think this can possibly be closed ... unless you think there is more should be done in regard encouraging Pa11y to be easier to extend.

**Comment by andymsuk** [comment]
@EmmaJP - happy to close?
