### ISSUE TITLE
Set up a pa11y dashboard that uses the a11y checks

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#104]
TODO:
- [x] get it running on heroku for starters
- [ ] @EmmaJP try and set it up within the BBC's staging infrastructure

**Comment by EmmaJP** [comment]
It was decided that setting up a Pa11y dashboard for others to use was beyond what we can currently accommodate.

It would be nice to provide some documentation on how to set-up a Pa11y dashboard with bbc-a11y available to it - ie. steps to hack the integrated HTML CodeSniffer etc.
