### ISSUE TITLE
Editorial significance of page areas

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#105]
Various standards require users to distinguish between "core content" and everything else. Although we could provide a fairly simple means of doing this (say, a CSS selector) for each standard check, that would introduce a fairly significant difference between bbc-a11y and similar tools like pa11y. Specifically, there is no way to configure how standards sniffs work in HTML_CodeSniffer, so you can no longer just point the linter at a URL and say "ignore these checks". Instead, you would be pointing the tool at a URL _and a configuration_.

Is it worth introducing this concept, even if it breaks compatibility with other a11y linters?

**Comment by mattwynne** [comment]
It seems to me that we need to address this in a later iteration, once we've stabilised the integration with pa11y / HTML_CodeSniffer (which I think we've already agreed are valuable enough to commit to).

The whole idea of being able to set up concrete, project-specific interpretations of these subjective rules is something that we'll get a lot of benefit from working out how to tackle, especially as / when we move into the screen-reader space. But I think we'll find it easier to think about once a lot of the existing loose ends are tidied up.

**Comment by EmmaJP** [comment]
For a BBC page using the ORB framework the core content should be within the element marked id="orb-modules", or role="main" if it exists.

**Comment by andymsuk** [comment]
Not sure what the issue is here... do we still want to do something?

**Comment by EmmaJP** [comment]
As no further work is intended in regard a general Pa11y integration, I'm closing this issue.

The concept of what is "core content" can be raised elsewhere if necessary. Though for BBC pages, it probably should be whatever is within the container with role="main".
