### ISSUE TITLE
Start maintaining release notes

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#111]
I think we need start maintaining a HISTORY.md or similar. For the last release we received this feedback from @greenc05:

> In future releases it would be nice to have a bullet point list to say what has changed or what is new in the release, when running this new version in News we now get 100 or so less errors (including some new ones) compared to the previous version but we aren't sure why exactly, having a brief summary of whats new in the release would help us work this out.

**Comment by joshski** [comment]
[HISTORY.md](https://github.com/bbc/bbc-a11y/blob/master/HISTORY.md) is born... thanks!
