### ISSUE TITLE
Recurse into iFrames

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#112]
Feedback from @greenc05:

> In addition I've also noticed that the tool doesn't look inside iframes, it would be really useful if it could do that, as we use iframes to load all the visual journalism content into the page.

Catherine do you have a good example of a page like that?

**Comment by greenc05** [comment]
Sure @mattwynne here's a couple of examples:

http://www.bbc.co.uk/news/uk-politics-eu-referendum-36027205
http://www.bbc.co.uk/news/uk-politics-eu-referendum-36271589

**Comment by joshski** [comment]
I couldn't get this working in ruby/phantomjs but it was easy in electron...
