### ISSUE TITLE
Headings: Content must follow headings - This is failing when content follows

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#113]
When I run the tool on http://www.bbc.co.uk/news I get the following errors which should not be errors

'''
Headings: Content must follow headings
No content follows: /html/body/div[2]/div[6]/div/div[4]/div[3]/div[2]/div[1]/div[1]/div[20]/h2
No content follows: /html/body/div[2]/div[6]/div/div[4]/div[3]/div[2]/div[1]/div[2]/div[7]/h2
'''

Both headings have a list below, maybe we are getting an error as the h2 and following content isn't in the same div? See screen shots.

<img width="869" alt="screen shot 2016-06-09 at 08 46 44" src="https://cloud.githubusercontent.com/assets/1061401/15922353/0c7f0dc8-2e1f-11e6-8ca2-cc4cbbff0c85.png">

<img width="1160" alt="screen shot 2016-06-09 at 08 50 35" src="https://cloud.githubusercontent.com/assets/1061401/15922432/8a9e46a6-2e1f-11e6-96d0-ba9e732b75c5.png">

**Comment by joshski** [comment]
@greenc05 I believe this issue is finally fixed for good. Please re-test using v1.1.0 if you get a chance, and reopen this issue if it's still a problem.

**Comment by greenc05** [comment]
Awesome, thank you @joshski I will try and check it out later today

**Comment by greenc05** [comment]
Tested and looks good thank @joshski

**Comment by greenc05** [comment]
Out of curiosity @joshski, if a heading has display none on it, and no content after it, will this rule fail?
