### ISSUE TITLE
Gettingstarted.md is missing some instructions

### ISSUE THREAD

**Issue by bmustill-rose-work** [bbc/bbc-a11y#114]
I and others have observed that gettingstarted.md does not contain all the commands required to start running tests.
When I attempted to run the sample tests in a11y.rb I received an error pertaining to /lib/bbc/a11y/js/bundle.js not existing.
I solved this by running
bundle exec cucumber
at which point everything started working as expected (Cucumber creates the required file).

**Comment by greenc05** [comment]
I would just update the instructions @bmustill-rose-work

**Comment by bmustill-rose-work** [comment]
Do you know if they will accept a PR? I assumed they wouldn't until the contracts were sorted out hence me just putting it as an issue.

**Comment by greenc05** [comment]
I would just trying creating one and we can hopefully merge it ourselves @bmustill-rose-work

**Comment by greenc05** [comment]
They are happy for us to contribute @bmustill-rose-work

**Comment by EmmaJP** [comment]
If you can generate a pull request, I can ask Josh how best to proceed in the mean time.

**Comment by joshski** [comment]
Thanks for your feedback @bmustill-rose-work 

> When I attempted to run the sample tests in a11y.rb I received an error pertaining to /lib/bbc/a11y/js/bundle.js not existing.

Are you cloning the bbc-a11y repository? or installing the gem from rubygems?

I just tried following through the instructions in gettingstarted.md and it worked out for me (see below). Are you doing something different?

```
➜  echo "gem 'bbc-a11y'" > Gemfile
➜  bundle install
Resolving dependencies...
Using addressable 2.4.0
Using mime-types-data 3.2016.0221
Using mini_portile2 2.0.0
Using rack 1.6.4
Using phantomjs 2.1.1.0
Using cliver 0.3.2
Using multi_json 1.11.3
Using websocket-extensions 0.1.2
Using bundler 1.11.2
Using mime-types 3.0
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using websocket-driver 0.6.3
Using xpath 2.0.0
Using capybara 2.7.0
Using poltergeist 1.9.0
Using bbc-a11y 0.2.0
Bundle complete! 1 Gemfile dependency, 17 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
➜  echo 'page "http://bbc.co.uk"' > a11y.rb
➜  bundle exec a11y
✗ http://bbc.co.uk
  * Form Interactions: Forms must have submit buttons
    - Form has no submit button: /html/body/header/div/div[1]/div[3]/form
```

**Comment by bmustill-rose-work** [comment]
I cloned it sorry.

**Comment by joshski** [comment]
No worries and thanks again. We should probably add something to clarify this point, you're not the first to mention it.
