### ISSUE TITLE
Title attributes standards need reviewing

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#125]
It seems we are being too aggressive with some of the checks here:

https://github.com/bbc/bbc-a11y/blob/master/features/check_standards/11_title_attributes.feature

Can we review the scenarios and make sure we've got good ones?

**Comment by JamieKnightBBC** [comment]
Hello,

Looking through them now i think if anything we're not being aggressive enough. For example the title on the iFrame won't be very useful.

Generally speaking if a title attribute is being used there is probably a better way. 

Hope that helps,

Jamie + Lion

**Comment by EmmaJP** [comment]
@JamieKnightBBC What could a title on an iFrame be used for? If it does not hurt accessibility then there is no reason it should trigger a fail in the tests. The guideline does not bar the use of title attributes per se, but rather specifies that they must not be used for critical information or repeat other visible or associated content.

**Comment by JamieKnightBBC** [comment]
Hello,

I'd argue it's hurts access by implying functionality which does not exist and leading developers to believe they have something covered when they do not.

For example, if something like share tools loaded an a iframe a developer may conclude that the title would be enough to do without a heading etc.

IMHO we should treat titles on an exception basis. They are bad unless on a form input and even then it's unlikely to be the best approach.

Hope that helps explain my view a bit.

Jamie + Lion

Sent from my iPhone

On 26 Jan 2017, at 18:06, EmmaJP <notifications@github.com<mailto:notifications@github.com>> wrote:


@JamieKnightBBC<https://github.com/JamieKnightBBC> What could a title on an iFrame be used for? If it does not hurt accessibility then there is no reason it should trigger a fail in the tests. The guideline does not bar the use of title attributes per se, but rather specifies that they must not be used for critical information or repeat other visible or associated content.

**Comment by EmmaJP** [comment]
I understand what you mean by developers thinking they have made something accessible when they haven't.  However, not every attribute or tag in HTML is solely about accessibility. That's why I asked if the title attribute has uses other than for tool tips.

**Comment by joshski** [comment]
OK well it sounds like we have this covered for now then. The iframe scenario was added since this issue was opened. Please reopen, or add new issues for anything that's not covered.
