### ISSUE TITLE
Cookie banner

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#127]
When I run the tests, I can't find the xpath for the majority of the errors, it seems that the cookie banner is causing the issue, I think we need to set the cookie before we run the tests

On this url you can see the issue:

a11y http://www.test.bbc.co.uk/news/front_page_beta

Any of the errors with div[7] you cannot find the xpath, this is the cookie div. If we set the cookie before running the tests as part of the process I believe this should resolve the issue.

**Comment by freeballoon** [comment]
Perhaps we use this as motivation to kick the cookie banner elsewhere (question the justification whether it needs to be the first readable content on the page), as it affects more than bbc-a11y
https://twitter.com/search?q=Cookies%20on%20the%20BBC%20website&src=typd

**Comment by samfrench** [comment]
In Responsive News cucumber suite they do:
```ruby
page.driver.set_cookie('ckns_policy', '001',  domain: 'bbc.com')
```

It seems that if the terminal xpath output is not the same as viewing the page in the browser then something is different on multiple visits to the page. Catharine suggested the xpath seems to get stuck on the cookie banner which indicates this differs on multiple page visits. A lot of the News testing tools set the cookie before checking the page, so we get a consistent experience.

**Comment by JamieKnightBBC** [comment]
This issues directly relates to: #160 which covers how to do this sort of pre-test setup.
