### ISSUE TITLE
Form Labels: Fields must have labels or titles

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#128]
This test fails even if it's a submit button, submit buttons do not require associated labels, please could the test be updated to have an exception of type submit, such as:

<input type="submit" value="Submit">

You can see this error here: a11y http://www.test.bbc.co.uk/news/front_page_beta

Field has no label or title attribute: /html/body/div[7]/header/div[4]/div/div[1]/div/div[1]/div[2]/form/div/input

**Comment by joshski** [comment]
Is this the same as #94?

**Comment by greenc05** [comment]
I think it could be, good spot @joshski

**Comment by joshski** [comment]
Fixed in https://github.com/bbc/bbc-a11y/pull/131
