### ISSUE TITLE
Dealing with ruby on a BBC machine and network connection

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#129]
I think someone familiar with the typical BBC set-up needs to provide some advice for doing the basic installation steps within the 'Getting Started' and 'Contributing' guides.

It could be as simple as having a non-Reith network connection, but I'm not the best person to advise.

**Comment by joshski** [comment]
@freeballoon said about installing within the BBC network:

[when downloading gems as documented in GETTINGSTARTED.md ...]

```Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed```

Needed to install GlobalSign root certificates, but also a key part was this:
`export SSL_CERT_FILE=/etc/pki/certificate.pem`

**Comment by freeballoon** [comment]
Alternatively (to `export SSL_CERT_FILE`) I've achieved the same effect by copying the GlobalSign root certificate *.pem* file to /usr/local/lib/ruby/2.3.0/rubygems/ssl_certs/

re: https://gist.github.com/luislavena/f064211759ee0f806c88#gistcomment-1892279

**Comment by JamieKnightBBC** [comment]
I think this can be closed as the project no longer has an ruby dependencies.

**Comment by joshski** [comment]
Agreed
