### ISSUE TITLE
karma command not found

### ISSUE THREAD

**Issue by andymsuk** [bbc/bbc-a11y#130]
## Summary

When following the guidelines for contributing, you may get an error about karma not being found if it's not installed.

## Expected Behavior

Follow guidelines for contributing
Run `bundle exec rake`
Expect tests to pass

## Current Behaviour

```bundle exec rake
bundle exec rspec && karma start --single-run
.....

Finished in 0.04987 seconds (files took 2.34 seconds to load)
5 examples, 0 failures

sh: karma: command not found
rake aborted!
Command failed with status (127): [bundle exec rspec && karma start --single-...]
/Users/smitha103/workspace/bbc-a11y/Rakefile:7:in `block in <top (required)>'
/Users/smitha103/.rvm/gems/ruby-2.2.4/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/smitha103/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/smitha103/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => unit
(See full trace by running task with --trace)
```

## Possible Solution

`npm install -g karma`
or update Rakefile to run
`bundle exec rspec && node_modules/karma/bin/karma start --single-run`
instead of 
`bundle exec rspec && karma start --single-run`

**Comment by reena2212** [comment]
I had the same issue and `sudo npm install -g karma-cli` worked for me

**Comment by joshski** [comment]
Thanks @andymsuk! Fixed in https://github.com/bbc/bbc-a11y/commit/642c5251b79ca93f6a525a134d1935ad324e1cdf

**Comment by joshski** [comment]
Incidentally I wouldn't recommend installing global modules, it just means we'all be running different versions of the test runner...
