### ISSUE TITLE
Show HTML snippets in pa11y

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#139]
See the HTML snippets:

![pa11y-dash-interior](https://cloud.githubusercontent.com/assets/22017/21268584/55c75d14-c3a7-11e6-9151-fd2d66b5e298.jpg)

...those aren't visible in the a11y version yet:

![screen shot 2016-12-16 at 15 50 40](https://cloud.githubusercontent.com/assets/22017/21268650/802c5fe6-c3a7-11e6-9798-30895e6e46e3.png)

**Comment by EmmaJP** [comment]
It was decided that setting up a Pa11y dashboard for others to use was beyond what we can currently accommodate. Hopefully some documentation will be provided on how to set-up a Pa11y dashboard with bbc-a11y available to it.

Leaving this open for future work that might improve bbc-a11y support for Pa11y and similar dashboards, in the output it provides.

**Comment by EmmaJP** [comment]
http://pa11y.org/news/2018/02/pa11y@5.0.0/ of interest ... as it implies Pa11y is still being looked after.

**Comment by EmmaJP** [comment]
Closing this issue, as for now no further work will be done toward having a general Pa11y dashboard. Individual product teams may wish to review the long standing branch to see how one might be implemented.
