### ISSUE TITLE
User Guide suggestions

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#151]
When installing bbc-a11y I needed more instruction...

Perhaps we could add this?

**Prerequisites**
If your project isn’t a node project, then install node.js…
If you don’t have a project you can install this in (e.g. you work with Morph) create a new directory you can use.

When running 'npm init' accept the default properties when prompted in the command line.

**Interactive mode**
In the code snippet it would help to have the folder path:
./node_modules/.bin/bbc-a11y http://www.bbc.co.uk --interactive

When the webpage opens, if the console is not already open, open this, click on the errors, then ‘CTRL’ click the HTML element and select ‘Reveal in Elements Panel’ from the options to locate them in the source code.

**Comment by joshski** [comment]
I've split up the guides and I think I've covered this @greenc05 -- thanks for your help, please reopen if I've missed anything

**Comment by greenc05** [comment]
Thank you @joshski
