### ISSUE TITLE
Text cannot be too small if it's displayed off-screen

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#152]
## Summary

It seems wrong for the 'Text size too small' rule to fail if the text is displayed off-screen.

## Possible Solution

If a text element fails as the text size is too small, is it possible to do a check to see if that element has well known CSS to make it display off-screen, and/or check to see if the **Grandstand visually hidden class** is applied to that element? 

And also the Grandstand display none class and/or CSS (e.g. display none) if this rule would also fail for hidden text?

Such as the following visually hidden grandstand class/and or CSS:
```
.gs-u-vh {
    position: absolute;
    width: 1px;
    height: 1px;
    margin: -1px;
    padding: 0;
    border: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
}

```
## Steps to Reproduce (for bugs)

When running the bbd-a11y tool (https://github.com/bbc/bbc-a11y)
I see the following error on http://www.test.bbc.co.uk/news/front_page_beta:

Minimum Text Size: Text cannot be too small
Text cannot be too small
Text size too small (10px): <span class=​"gs-u-vh">​BBC News​</span>​ 
//a[@id='brand']/span[2]
Text cannot be too small
Text size too small (10px): <h4 class=​"gs-u-vh">​Related content​</h4>
//div[@id='u777787601808086']/div/div/div/div[1]/div/div[1]/div/div/div/div[3]/div/div/h4

**Comment by joshski** [comment]
Thanks @greenc05 

I think @EmmaJP has mentioned before that off-screen text shouldn't need to be tiny, so it wouldn't fail the minimum text size validation. Now that we can [hide these kind of errors](https://github.com/bbc/bbc-a11y/blob/master/USING.md#hiding-errors) fixing this seems like it's not worth the effort so I'm closing it. Please reopen if you disagree.

**Comment by greenc05** [comment]
Hummm these errors will be on every page of the News website, I disagree @joshski, however you know better that I do with regards to how much effort this would be to implement. Thank you

**Comment by joshski** [comment]
It's not the effort, it's more about principle! Is there a reason you can't stop making the text tiny with css? I'd like to understand

**Comment by greenc05** [comment]
@joshski It is no longer thought of as best practice to write local/project based CSS (if it can be helped) if using a framework such as Grandstand, this would add to page weight/load, maintenance effort etc. When you work with Morph/Grandstand (the new fancy way of developing at the BBC), to specify typography, you apply a class directly to the html element such as 'gel-brevier', this would give the specified element the 'Brevier' typography (otherwise I believe it inherits font 100% from the CSS reset style sheet). I will have to specify classes such as this to all visually hidden text in order for this rule to pass or add a line of CSS to the Grandstand visually hidden CSS - which would mean I am adding a line of CSS that everyone in the BBC will get and on every site - you may say no big deal, though performance is key and if don't have to add a line of CSS that is only for this rule to pass then that is good. Also if this visually hidden text was to be shown it would take the appearance of what ever random typography class I have added if I went for that option (as these would not be specified by design). Hope that makes sense!

**Comment by freeballoon** [comment]
@joshski re "why tiny text" - this approach has its foundations in the YUI Accessibility Blog from 2006 http://yaccessibilityblog.com/library/accessible-hiding-content.html (503) or perhaps even earlier. I see no evidence to support the justification of using `height: 1px` and I feel it's probably a fallback mechanism of "if the other rules fail, then at least we'll render only one inconspicuous pixel".

WebAIM write (although they're still claiming `clip` is "new", so this advice isn't likely to be current) at http://webaim.org/techniques/css/invisiblecontent/
> width:1px; height:1px; overflow:hidden; tells the browser to make the element 1px by 1px in size and to visually hide everything that does not fit into these dimensions. While this is a likely a little overkill and can probably be omitted in most circumstances, there are a few instances where positioning may be disabled, but all other styles remain enabled. In this case, the element will remain in its original position, but will only take 1 pixel of space.

Perhaps it's time to (empirically) disprove 1px and render offscreen (arguably above the screen at top:-500px etc to help rtl?) text at regular size? Thoughts @greenc05 @EmmaJP?

**Comment by EmmaJP** [comment]
@greenc05 An example of the clipping technique is included and recommended in http://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/visible-on-focus.shtml, which also states that both clipping or negative positioning are accessible.

The clipping technique does not require the inherited font size to be changed. And the required position absolute means the element size will not affect the page flow. This means that the change of font size is not needed. It would be incorrect to adjust the checks bbc-a11y does to make an exception for a technique. If you wish to ignore those errors, that is up to you.

Incidentally, at some point in the not too distance future, the technique will need to change to use clip-path, but not just yet as the support is still patchy.

**Comment by greenc05** [comment]
Unless I'm totally misunderstanding here, that's basically the CSS we are using @EmmaJP (See top of PR) and the rule fails as we are not specifying a font size as it inherits from the CSS reset stylesheet font size 100%, and therefore we need to specify a font here for this rule to pass, which is what I'm disagreeing with.

**Comment by EmmaJP** [comment]
@greenc05 Clip alone does not seem to affect the text size: http://codepen.io/anon/pen/mRwEBO. 
For news pages, the font-size on body is 14px or 16px (depending on the iframe). For text to have a size of 10px or smaller, something is resetting that size somewhere.

@joshski , can we double check that the font-size the test sees is not being affected by the element size.

**Comment by greenc05** [comment]
Yeah thanks @EmmaJP The computed font size when I inspect one of the elements in question is 10px, I believe it's inheriting a font size of 62.5% from the body. Boo boo

**Comment by joshski** [comment]
We use jquery to compute the size, which does a pretty good job I think. So is the conclusion that the font is actually too small? 😀

**Comment by greenc05** [comment]
Yes the font size is too small, though it comes back to my point, that I now have to apply a font to this element for this rule to pass, which is what I disagree with, though it seems like just me who thinks this is not a good practice.

**Comment by EmmaJP** [comment]
@greenc05 possibly not - if they are the icons in the promotion panel coming into the page with ORB.
