### ISSUE TITLE
Make it easier to run bbc-a11y

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#153]
At the moment the docs mention running bbc-a11y like this:

```
./node_modules/.bin/bbc-a11y
```

We'd prefer that to be simpler, i.e:

```
bbc-a11y
```

We talked in slack about maybe using a version-independent shim that spawns a process forwarding the latter to the former. Having thought about this more, I think we shouldn't do that, it's more confusing. We should just do what everybody else does, document how to install globally, which is convenient for non-technical users, but then also warn about the risks of using a global version when your project uses a11y, and how to add an npm script entry in your package.json.

**Comment by EmmaJP** [comment]
Can we shout out to others devs in Slack to find out preferences and previous experience? If nothing comes back then go with what seems best.

**Comment by joshski** [comment]
This is fixed, the [validating a website guide](https://github.com/bbc/bbc-a11y/blob/master/guides/using/validating-a-website.md) mentions global installation, whereas the [validating your project guide](https://github.com/bbc/bbc-a11y/blob/master/guides/using/validating-your-project.md) talks about local installation.
