### ISSUE TITLE
Feature to respond with a warning rather than an error

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#161]
For some guidelines we may be able to check for things that are bad practice, such as an image name in an alt attribute, and flag them with a warning.

It may also be helpful to flag hidden errors with a warning.

**Comment by joshski** [comment]
This scenario was mentioned in [another issue](https://github.com/bbc/bbc-a11y/issues/109) as a good candidate for warning rather than error:

```
Scenario: Non-input tag with title attribute
    Given a page with the body:
      """
      <a href="close" title="Close Button">
        <img src="close.png" />
      </a>
      """
    When I validate the "title attributes only on inputs" standard
    Then it **warns** with the message:
      """
      Non-input element has title attribute: /html/body/a
      """
```

**Comment by EmmaJP** [comment]
Yep, that should be a warning. It's not strictly a fail, but if they are trying to use the title attribute to make the image accessible, then there are much better ways to code that. The title attribute does not make it accessible and is largely ignored by screen readers (default settings) these days.
