### ISSUE TITLE
JUnit reporter

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#170]
Because the JUnit test report format is so ubiquitous, it might be worth bbc-a11y including a built-in reporter so that it's dead easy to plug bbc-a11y into CI tools like Jenkins.

We could use this to implement this feature relatively easily: https://github.com/davidparsson/junit-report-builder

**Comment by EmmaJP** [comment]
@andymsuk do you still think this would be useful?

**Comment by andymsuk** [comment]
I've built it in to [a11y-tests-web](https://github.com/bbc/a11y-tests-web) which Sounds and iPlayer are now using. If anyone else thinks it's useful, we could look to make it available in bbc-a11y itself too.

**Comment by greenc05** [comment]
@jroebu14 would this be useful to simorgh?

**Comment by andymsuk** [comment]
I was under the impression that "simorgh" were using a11y-tests-web (but with local config files rather than ones committed to the repo)

**Comment by greenc05** [comment]
Could you confirm @jroebu14 please?

**Comment by jroebu14** [comment]
tbh I'm not sure about that. The only evidence if bbc-a11y I see are https://github.com/bbc/simorgh/blob/latest/a11y.js and https://github.com/bbc/simorgh/blob/latest/package.json#L8

I'm unsure how to confirm we are using a11y-tests-web

@greenc05 @andymsuk
