### ISSUE TITLE
Tab index message should be more accurate

### ISSUE THREAD

**Issue by mikeposh** [bbc/bbc-a11y#171]
## Summary

The [Tabindex standard](http://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/tabindex.shtml) says "tabindex values of 0 must not be used on elements that are not focusable by default ... There are no circumstances in which it is not better to use a natively focusable control such as a `<a>` or `<button>`."

The rule uses `var baddies = $("*[tabindex='0']:not(input, button, select, textarea, a)");` to pick out the rejected cases.

The message produced when tabindex=0 is set on non-focusable-by-default element is:

"Non-field element with tabindex=0", "Elements with zero tab index must be fields"

and the rule itself is called `elementsWithZeroTabIndexMustBeFields`.

I would interpret "field" as "input field" and wouldn't expect it to include links and buttons, so I think the output is a bit misleading and would be better as:

`elementsWithZeroTabIndexMustBeFocusableByDefault`

With short text: "Non-focusable element with tabindex=0"
and rule name: "Zero tab index must only be set on elements which are focusable by default"

Alternatively, "natively focusable" could replace "focusable by default".

## Expected Behavior

When running interactively and an element violates the rule, e.g.

`bbc-a11y https://m.bbc.co.uk/weather/2649255 --interactive`

you should see:

"Zero tab index must only be set on elements which are focusable by default"
"Non-focusable element with tabindex=0: [element]"

## Current Behavior

When running interactively and an element violates the rule, you see:

"Elements with zero tab index must be fields"
"Non-field element with tabindex=0: [element]"

## Possible Solution

Change the appropriate text and filenames in:

https://github.com/bbc/bbc-a11y/blob/master/lib/standards/index.js
https://github.com/bbc/bbc-a11y/blob/master/lib/standards/tabIndex/elementsWithZeroTabIndexMustBeFields.js
https://github.com/bbc/bbc-a11y/blob/master/features/check_standards/10_tab_index.feature

## Context & Motivation

I was running the rule and was surprised by what was reported. Eventually found the actual standard and then understood was was meant.

## Your Environment

* Version used: 1.2.2
* Link to your project: https://github.com/bbc/weather-web-responsive

**Comment by joshski** [comment]
Lovely, thanks @mikeposh!

I've tried to follow your suggestion here, please confirm this is what you meant:

https://github.com/bbc/bbc-a11y/commit/e3b3c6c99a73f7a864b9a7e09b9edf63258528aa

**Comment by joshski** [comment]
This is merged now, please reopen if I missed anything.

**Comment by mikeposh** [comment]
Looks perfect, thanks Josh!
