### ISSUE TITLE
Does it check the URL as if it has never been viewed before?

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#176]
As [mentioned by @greenc05](https://github.com/bbc/bbc-a11y/issues/165):

> I also assume the tool checks the url as if it has never been viewed before? e.g. without any location settings or any other assumed knowledge

There are no scenarios covering this, so I'm not entirely sure what the answer is. There is a scenario covering caching, but not cookies or location settings etc.

**Comment by EmmaJP** [comment]
I presume cookies and location etc. would be reset and set afresh in the pre-test step in development?
