### ISSUE TITLE
Template for semi-automated checks

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#190]
It may be possible to automate a check with the assistance of a little information provide via a parameter or config of some sort.

Page title might lend itself well to this, if a formula for the title were provide. For example, many BBC responsive pages will use a formula similar to "BBC - [site/brand name] - [H1 text]" to populate the title tag, where [site/brand name] should match the alt text on the brand logo, and [H1 text] the contents of the H1 tag.

The check that a page title exists is straightforward to automate and would render a boolean result. 

The check that a title identifies the main content is complex. However, comparison with a provided formula could raise a warning if the formula is not met. The check could also compare the page title to other some other pages under the same URL space (bbc.co.uk/tld/xyz) to ensure they are not all the same. And the formula should probably reference the page H1 in some way.

**Comment by joshski** [comment]
One very general way this could work is if the user supplies a function, which can then be picked up by a standards check:
```js
page("http://www.bbc.co.uk/news/uk-england-humber-39233017", {
   pageTitleFormat: $ => $('h1').text() + ' - BBC News'
})

**Comment by joshski** [comment]
Merged an example of a "semi-automated test" in https://github.com/bbc/bbc-a11y/commit/4c1c6c4faf7111de2144584d76b94eb38e212f2d
