### ISSUE TITLE
Improve the "implementing code changes" documentation

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#206]
This needs some more details:

https://github.com/bbc/bbc-a11y/blob/master/guides/contributing/code-changes.md#implementing-code-changes

e.g.

* where are the feature files?
* how do I run the scenarios?
* how do I understand the architecture of the code?

**Comment by EmmaJP** [comment]
@andymsuk @llouisetaylor could you both look at the existing docs on implementing code changes and comment of whether or not you think it is detailed enough? Or whether it could benefit from some additional information on how bbc-a11y hangs together as a codebase?

**Comment by andymsuk** [comment]
I'm too used to the codebase now. @llouisetaylor ?

**Comment by greenc05** [comment]
One for you too possibly @jroebu14 ?

**Comment by llouisetaylor** [comment]
There's things I don't understand about the cucumber tests. I still don't understand how questions with a `manualTest` map to implementation? Maybe it would be helpful to have some outline about how those questions work.

In general probably an outline of the directories would be really helpful e.g. https://github.com/bbc/sounds-web/#directory-structure
