### ISSUE TITLE
Run bbc-a11y on BBC CI

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#207]
I had a go at making electron work on CentOS 7 to support teams using that OS as part of their CI setup. I got stuck trying to run electron on CentOS on this branch:

https://github.com/bbc/bbc-a11y/tree/centos

The Dockerfile on that branch sets up a CentOS box and installs everything theoretically necessary to run bbc-a11y -- however electron apps are not working. The electron main process crashes without any feedback when the electron [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) is instantiated.

There may be some value in looking at alternative docker solutions to running xvfb, such as this one based on CentOS 6: https://hub.docker.com/r/jniesen/centos-firefox-jenkins-slave/~/dockerfile/

It might also be worth looking at alternatives like:

* Hosting a11y outside the BBC network and using HTTP tunnelling like CI builds using BrowserStack
* Using AWS Lambda or a similar service to spawn ad-hoc machines

**Comment by EmmaJP** [comment]
Someone else mentioned headless Chrome ... perhaps a configurable choice of "browser" is an option. Just noting it so it's not forgotten.

**Comment by EmmaJP** [comment]
https://hub.docker.com/r/bbca11y/bbc-a11y-docker/ has been set-up and can be used.

iPlayer, Children's, and Education are all using bbc-a11y via Joseph's dockerfile. News have also been looking to do the same. All are aware of the new dockerfile location and the imminent release of bbc-a11y v2.0.
