### ISSUE TITLE
Push official Dockerfile to dockerhub

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#219]
A Dockerfile exists for running bbc-a11y:

https://hub.docker.com/r/wildlyinaccurate/bbc-a11y-docker/~/dockerfile/

We should host this under a bbc-a11y dockerhub account.

**Comment by EmmaJP** [comment]
bbca11y account set up

**Comment by EmmaJP** [comment]
Would be good to add versioning to the dockerfile to match the bbc-a11y version.

**Comment by EmmaJP** [comment]
It would also be good to add a little something about how the Docker works into the documentation. Perhaps under the 'contributing - changing code' stuff.

**Comment by EmmaJP** [comment]
I think we need the Docker set-up to be an automated build, which it currently isn't, and I can't seem to get it to work. I don't know which of the many settings or things to read I have missed, but the new set-up does not yet seem to be something the production teams can use.

**Comment by EmmaJP** [comment]
Misunderstood purpose of Docker hub's automated build. The bbca11y dockerfile can be used from the repo at https://hub.docker.com/r/bbca11y/bbc-a11y-docker/ using the instructions at https://github.com/bbc/bbc-a11y/tree/master/docker.

Presume the dockerfile and documentation will be updated if anything about the full release of bbc-a11y causes any changes to be needed.

**Comment by EmmaJP** [comment]
It is possible to tag docker versions. So the bbc-a11y release process has been documented with instructions for updating the dockerfile and tagging the versions included.
