### ISSUE TITLE
Run a11y on pa11y on AWS

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#220]
Looks like [Lightsail with RDB](https://lightsail.aws.amazon.com/ls/docs/overview/article/using-lightsail-with-other-aws-services?fid=497AF2985B3BB229-09E697523548CCEC) might be the way to go

**Comment by EmmaJP** [comment]
It was decided that setting up a Pa11y dashboard for others to use was beyond what we can currently accommodate.

It would be nice to provide some documentation on how to set-up a Pa11y dashboard with bbc-a11y available to it - ie. steps to hack the integrated HTML CodeSniffer etc.
