### ISSUE TITLE
Update to install documentation

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#229]
Some BBC users may not have permission to install globally.

Update docs to explain how to install locally and set up an alias. In addition to current install instructions.

I followed https://jonsuh.com/blog/bash-command-line-shortcuts/ and found https://www.nucreative.co.uk/how-to-create-command-line-shortcuts-to-folders/. A brief version of similar info should suffice.

**Comment by EmmaJP** [comment]
Could be included with #255

**Comment by ermi-ltd** [comment]
+1
