### ISSUE TITLE
Circle CI: stop using it or migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#248]
Both circle _and_ travis are running CI builds on commits to bbc-a11y branches. Technically we only need one, and [Circle CI is grumbling](https://circleci.com/gh/bbc/bbc-a11y/447) about deprecating support for our legacy config, like this:

```
Please start migrating this project to CircleCI 2.0.
```

If it's easy, upgrade Circle, otherwise Travis should suffice.

**Comment by EmmaJP** [comment]
Removed Circle CI during handover session while pushing through https://github.com/bbc/bbc-a11y/releases/tag/v2.1.0
