### ISSUE TITLE
Help and Version commands for CL

### ISSUE THREAD

**Issue by EmmaJP** [bbc/bbc-a11y#263]
I think it would be helpful to provide a way for users to know which version of bbc-a11y they have installed and to get some help prompts in the CL. Currently `bbc-a11y help` and `bbc-a11y version` both try to test those as URLs, and `bbc-a11y` alone reports there is no a11y.js config file and offers a link to the github.

I believe such things are fairly common practice and would be useful to implement or improve.

**Comment by andymsuk** [comment]
Hi @EmmaJP 

I think the following commands give you what you're after, and are fairly standard naming.

```
> bbc-a11y --help

 Usage: bbc-a11y [options] <urls>

  Options:

    -V, --version              output the version number
    -i, --interactive          show browser window and leave open for debugging
    -m, --manual               include manual tests
    -w, --width <pixels>       override viewport width
    -c, --config <config>      path to config file
    -r, --reporter <reporter>  json or [path to custom reporter module]
    --coverage <list|table>    lists all tests with a description of each test
    -h, --help                 output usage information
```

```
> bbc-a11y --version
2.1.0
```

However, I acknowledge this isn't actually documented anywhere, so I've opened https://github.com/bbc/bbc-a11y/pull/264 to add it.

Please take a look at that PR and let me know if that helps.

**Comment by EmmaJP** [comment]
Totally me having holiday brain and forgetting to put a double dash in front of a command ... but definitely helpful to have it in the documentation! Thanks.
