### ISSUE TITLE
Feature request: pre-run hook

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/bbc-a11y#272]
## Summary

We would like to be able to run arbitrary code before running the accessibility suite, as a lot of what we build isn't actually rendered until the user has interacted in some way.

We've made similar improvements to [Wraith visual regression testing](https://github.com/BBC-News/wraith/releases/tag/v2.6.0) by providing hook functionality.

## Possible Solution

It should be fairly simple to extend the API we have, ie

```js
page('http://www.bbc.co.uk', {
  skip: [
    'Headings: Content must follow headings'
  ]
})
```

...becomes:

```js
page('http://www.bbc.co.uk', {
  skip: [
    'Headings: Content must follow headings'
  ],
  before: (webdriver) => {
    require('./before.js')(webdriver);
  }
})
```

And in before.js:

```js
module.exports = (webdriver) => {
    webdriver.select('button').click(); // or whatever the API is for the headless browser we use
};
```

## Context & Motivation

We want to check the accessibility of our content, but a lot of what we do is highly interactive, so the initial page may just contain an input and a button, so not much to scan. When the form is filled in, we dynamically render complex charts, various sections of results, etc.

Currently, BBC-a11y is just not very useful to Visual Journalism without being able to perform an interaction prior to the scan.

Thanks!

**Comment by ermi-ltd** [comment]
Is it possible to achieve the same effect using the URL / history API as the user moves through states?

This is how I have been using a11y to test various in page states on other projects.

**Comment by ChrisBAshton** [comment]
Not without re-engineering our projects to use the history API. And our results are typically very custom, e.g. based on user's height & postcode or something, so we wouldn't just visit `mypage.html#results` because results will vary.

**Comment by ermi-ltd** [comment]
How does the user share thier result?

**Comment by ChrisBAshton** [comment]
There's no custom share on that page, so indeed you can't share a custom URL that preloads the "My name is Ama, and there were 5 girls with that name in 2017" experience. Sometimes we _do_ have a custom share like that but we usually just link to the page's 'vanilla' state, as there's little benefit in pre-loading another person's experience; it's all about getting your own personal experience by interacting with the thing.

Outside of our immediate use case, there are other good uses for a 'hook' mechanism, e.g. reloading a page with a specific HTTP header, or with a specific cookie, or without JavaScript, or with adverts. We found it very useful in Wraith!

**Comment by EmmaJP** [comment]
Is there not already a means to do something like this? It's all javascript based, so it should be possible.

See https://github.com/bbc/bbc-a11y/blob/master/guides/using/using-bbc-a11y-in-your-project.md#advanced-usage-manually-setting-up-the-browser-window

Could you use this?

**Comment by ermi-ltd** [comment]
Looks very similar.

**Comment by andymsuk** [comment]
I would suggest the same as @EmmaJP. `visit` option sounds like what you need, @ChrisBAshton.

**Comment by ChrisBAshton** [comment]
Oh it exists! Thanks. Didn't see anything in the main README so I never knew about this feature.

This should be all I need! 👍 Should we document it elsewhere or just close this issue?

**Comment by ermi-ltd** [comment]
This approach is nicer. It doesn’t suffer from the same issues around webdriver as it appears to be executed inside the page by the browser not within the a11y tool itself.

Not quite the same, but possible to achieve the same effects.

**Comment by EmmaJP** [comment]
It isn't in the main README, but it is in the docs for experienced devs. 

I would agree that the documentation should probably be revisited a little.

**Comment by EmmaJP** [comment]
I've made a small change to the main README, to indicate that the second link includes information about more advanced features. As it is such a minor change and simple to revert, I committed it directly to master.

@ChrisBAshton if `visit` meets your requirement, could you please close this issue.

**Comment by ChrisBAshton** [comment]
Sure, thanks
