### ISSUE TITLE
Coverage documentation links to insecure urls

### ISSUE THREAD

**Issue by lbod** [bbc/bbc-a11y#279]
## Summary

https://github.com/bbc/bbc-a11y/blob/master/guides/coverage.md links to http pages when should be https.

## Expected Behaviour
I want a BBC website page that shows this coverage information with links to guidelines that work across most browsers. 

## Current Behaviour
https://github.com/bbc/bbc-a11y/blob/master/guides/coverage.md links to non secure urls for each guideline, the bbc website fails to load due to a javascript issue with appcache over non HTTPS

No content is loaded.

## Possible Solution

The BBC should enforce HTTPS redirects and provide a public BBC website web page for this coverage documentation.

## Steps to Reproduce (for bugs)

1. load https://github.com/bbc/bbc-a11y/blob/master/guides/coverage.md in a browser, firefox or chrome
2. click any link e.g. http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/principles 
3. See error:

```
[Deprecation] Application Cache is restricted to secure contexts. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
12:39:27.887 cache.js:58 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.init (cache.js:58)
    at bv (jquery-1.7.2.js:16)
    at Object.fireWith (jquery-1.7.2.js:16)
    at ready (jquery-1.7.2.js:16)
```

## Context & Motivation
It's a very useful document and should be promoted as general practice when considering user interface testing.

## Your Environment
It works on IE11 and on Edge.
It doesn't work on latest firefox and chrome, I haven't tried close to most common environments as yet but Win 7 FF and Chrome failed and Win 10 too.
Local mac testing both FF and Chrome fail.
Cloud testing on Mac high sierra with FF/chrome was the same, safari 11.1 apparently ok!

* Version used:
* Operating System and version:
* Link to your project:

**Comment by ChrisBAshton** [comment]
Fixed in #280
