### ISSUE TITLE
<abbr> tag uses "title" and currently fails the title attribute scenario

### ISSUE THREAD

**Issue by sbeaumontweb** [bbc/bbc-a11y#281]
## Summary

`<abbr>` tags, as standard, use a "title" attribute to provide an expanded version of an abbreviation: https://www.w3.org/TR/html52/textlevel-semantics.html#the-abbr-element

Currently, unexpected failures are happening on our abbreviation tags because the current code does not include <abbr> in the whitelist for tags that are allowed to use a "title": https://github.com/bbc/bbc-a11y/blob/8ccd025ba26b3b11cc22aafdb81ed6b04a566c21/lib/standards/tests/titleAttributesOnlyOnInputs.js

## Expected Behaviour

`<abbr title="Sophie Beaumont">Sophie</abbr>`

Should not trigger a failure of the scenario "Non-input element has title attribute", as `<abbr>` with a title is semantically correct, and screen readers will read out the title of the tag instead of the abbreviation.**

## Current Behaviour

`Non-input element has title attribute: //div[@id='u765878345439809']/div/div[2]/div/div/div/div[2]/ul[1]/li[13]/span[2]/abbr`

Above error occurs in any situation where `<abbr>` tag is used with a title attribute.

## Possible Solution

Add `<abbr>` to the whitelist in the above mentioned test.

## Context & Motivation

We use a list of players in our Lineups for our scorecard pages: https://www.test.bbc.co.uk/sport/rugby-union/match/EVP2632964

Each player's name uses an `<abbr>` tag which allows us to use a shortened version of the name for visual display purposes only. (No truncation or wrap needed on mobile breakpoint)

Thanks. :)

 ** https://github.com/bbc/bbc-a11y/issues/281#issuecomment-443755600

**Comment by andymsuk** [comment]
Hi @sbeaumontweb 
Thanks for raising the issue.
Your possible solution looks like the best! Do you want to raise a PR to fix it?
Thanks!

**Comment by sbeaumontweb** [comment]
" and screen readers will read out the title of the tag instead of the abbreviation."
I should rectify this incomplete statement - screen reader settings can be changed as such that they read out the title of the abbreviation instead of the content of the tag. Some are not set this way. However, responsible use of the title attribute by the standards (don't repeat information or use for critical information) shouldn't harm accessibility as the information inside the tag would still be valid.

**Comment by ermi-ltd** [comment]
Most AT won’t read the title which is probably a good thing as the information is intended to be suppmental not critical.

If it’s important information a label would be more appropriate. If it’s fluff that also isn’t present visually, I don’t understand what it’s there for.

The test cannot check for appropriate or contextual use so I am very hesident to consider it a complete test.

At the least I think this should warn the user to check or ask themselves the question on if the content in the title is essential to understanding the content / context.

This has been written about a fair bit in other places: 

https://openinclusion.com/blog/presenting-abbreviations-acronyms-for-screen-reader-users/

This answer also links out to the spec and the various comments about relying on titles on abbr etc.

https://stackoverflow.com/a/32892825

Some additional views and comments from twitter here: https://twitter.com/jamieknight/status/1069581095128231936?s=21

BBC-a11y isn’t a validator of the specification. It’s a tool which tries to help teams deliver great experiences.

While an abbr and optional title fall within the spec, the risk of misuse and the relatively edge case nature may make it simpler to do without then.

I’d support moving it from an error to a warning, as an in between position.
