### ISSUE TITLE
npm audit failure against jquery

### ISSUE THREAD

**Issue by pjlee11** [bbc/bbc-a11y#289]
## Summary

There is a moderate vulnerability in the dependency `jquery@3.3.1` with Prototype Pollution as per https://www.npmjs.com/advisories/796

## Expected Behaviour

`npm audit` shouldn't fail on this package.

## Current Behaviour

![image](https://user-images.githubusercontent.com/7791726/56591370-8631c880-65e0-11e9-8a64-4eb90e0d64d6.png)

## Possible Solution

Bump jquery version to `3.4.0`

**Comment by pjlee11** [comment]
PR fix in fork https://github.com/bbc/bbc-a11y/pull/290 could someone with write access review and approve please

**Comment by oluoluoxenfree** [comment]
Merged already so I will close this!
