### ISSUE TITLE
Automate visible on focus standard

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#30]
Split off from #11

See https://github.com/cucumber-ltd/bbc-a11y/blob/master/standards/11_visible-on-focus.md

**Comment by mattwynne** [comment]
I think potentially this could be automated, I'd need to do some experimentation to find out.

**Comment by IanPouncey** [comment]
This would be a high value you test if it could be automated.

**Comment by EmmaJP** [comment]
Selenium has a property it can detect that informs whether an element is visible or not.  This might be helpful.

**Comment by joshski** [comment]
Fixed in 30572a29aefc86a338548649583f6c55b7ec6b87
