### ISSUE TITLE
Security vulnerability in httpism package

### ISSUE THREAD

**Issue by hindsc52** [bbc/bbc-a11y#301]
`npm audit` has found a high vulnerability is a dependancy used in the `httpism` package at the version used by bbc-a11y. Introduced via https://www.npmjs.com/package/https-proxy-agent

![image](https://user-images.githubusercontent.com/14273378/67115345-e4c5b100-f1d5-11e9-851e-a23b84098c52.png)

Related: https://github.com/browserstack/browserstack-local-nodejs/issues/87

**Comment by andymsuk** [comment]
Waiting on the middle dependency to update:
https://github.com/featurist/httpism/issues/50
