### ISSUE TITLE
http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/summary shows white page

### ISSUE THREAD

**Issue by kylekirkby** [bbc/bbc-a11y#307]
http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/summary shows white page on Chrome/Firefox (Ubuntu 18.04). Content displays briefly then fades out.. :) 

![bbc-a11y](https://user-images.githubusercontent.com/4564433/68293078-1fa85f80-0085-11ea-84b0-fd52d51efe3b.png)

**Comment by andymsuk** [comment]
Hi @kylekirkby.

That is the old URL - the new URL is https://www.bbc.co.uk/accessibility/forproducts/guides/mobile/ and #297 is already open to update all the links to the new site.

**Comment by kylekirkby** [comment]
@andymsuk - thank you!
