### ISSUE TITLE
Update a11y documentation links in console warnings

### ISSUE THREAD

**Issue by thekp** [bbc/bbc-a11y#315]
# Summary
When running this command `bbc-a11y https://www.test.bbc.com/pidgin/popular/read` I received this console warning: 
![image](https://user-images.githubusercontent.com/30599794/80621506-4c8b6d00-8a3f-11ea-83a1-d1f003f61e86.png)

It is a helpful console warinng, however the link it suggested: https://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/structure/headings
does not work 👀 

## Expected Behaviour

After some further investigation, I found what I believe to be the correct link: https://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/headings.shtml

## Current Behaviour

It is logging a broken link: 
![image](https://user-images.githubusercontent.com/30599794/80622067-2dd9a600-8a40-11ea-8836-90961f4ad439.png)

## Possible Solution

Short-term we could possibly update the links in the CLI tool.

A better solution is probably to find out where the routing is done and redirect them to the new links.

## Steps to Reproduce (for bugs)
1. Run `bbc-a11y https://www.test.bbc.com/pidgin/popular/read` in terminal
2. View the console warnings
3. Click the link provided in the console warning
4. See the broken page.

## Context & Motivation
It didn't affect me too much as I was able to find the new URL quite easily. 

## Your Environment
* Version used: 2.4.0
* Operating System and version: MacOS v10.12.6 (16G2136)
* Link to your project: https://github.com/bbc/simorgh

**Comment by JamieKnightBBC** [comment]
Hi,

Ah, this is something we know about. The old guidelines site is down while the new site is awaiting a final URL + redirection to be setup.

The link will work again shortly. The link your suggestion is to the HTML standard rather than the Mobile Access Guidelines.

I would suggest we leave this be as the old link will be fixed in the not too distant future and it remains the canonical URL for that content.

J&L

**Comment by thekp** [comment]
> I would suggest we leave this be as the old link will be fixed in the not too distant future and it remains the canonical URL for that content.

Excellent, Thanks for the update @JamieKnightBBC :)

**Comment by EmmaJP** [comment]
There is already an issue and related PR to cover the changes to guideline URLs to the new site that was published last year. Something about it needed resolved and I couldn't figure it out. 

Presuming the new site will still be used, and the merge issues can be resolved, it is ready to go.

Refer PR #297
