### ISSUE TITLE
[Security] Vulnerability in electron package

### ISSUE THREAD

**Issue by FK78** [bbc/bbc-a11y#323]
## Summary

The `electron` package has four security vulnerabilities.

- https://github.com/advisories/GHSA-6vrv-94jv-crrg
- https://github.com/advisories/GHSA-m93v-9qjc-3g79
- https://github.com/advisories/GHSA-h9jc-284h-533g
- https://github.com/advisories/GHSA-f9mq-jph6-9mhm

## Possible Solution

Update `electron` to a patched version (>=7.2.4).

**Comment by nicholasgriffintn** [comment]
This should be resolved by: https://github.com/bbc/bbc-a11y/pull/347
