### ISSUE TITLE
Automate table standard

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#34]
Split off from #11.

See https://github.com/cucumber-ltd/bbc-a11y/blob/master/standards/16_table.md

**Comment by mattwynne** [comment]
This looks like something we could at least partly automate - most of that algorithm looks pretty objective to me. @IanPouncey you've marked this as Manual in the standard doc. What are your thoughts?

**Comment by IanPouncey** [comment]
It would be great if this can automate most of this. The hardest part is, I guess, the differently coloured rows, but if this is possible it would be great to have. While it can be manually tested it is quite involved.
