### ISSUE TITLE
CI builds have stopped

### ISSUE THREAD

**Issue by andymsuk** [bbc/bbc-a11y#349]
## Summary

CI builds (e.g. PR checks) have stopped.

## Expected Behaviour
Checks are automatically carried out on new PRs

## Current Behaviour
No checks are automatically carried out on new PRs as, since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased

## Possible Solution

Use GitHub actions instead (like on https://github.com/bbc/a11y-tests-web) since this is a public repo.

## Steps to Reproduce (for bugs)
1. Open a PR

**Comment by nicholasgriffintn** [comment]
Fixed in the PR #358
