### ISSUE TITLE
Bookmarklet for browser integration

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#58]
Good first pass, and will let it run in any browser.

**Comment by joshski** [comment]
Once we have a formal way of bundling the bbc-a11y standards with a custom build of HTML_CodeSniffer, we can use their bookmarklet "for free"... I'll add documentation for how to grab a bbc-a11y-enabled bookmarklet at that time.

**Comment by EmmaJP** [comment]
With bbc-a11y becoming an electron based-app, is there still any need for this?

**Comment by joshski** [comment]
I'm not sure there is a need for this, no. Anyone disagrees can reopen.
