### ISSUE TITLE
Run with JS on and off

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#61]

**Comment by joshski** [comment]
This is not easy given support in electron and the current shape of our code. How important is it?

https://github.com/electron/electron/issues/5838

https://github.com/electron/electron/issues/7529

**Comment by EmmaJP** [comment]
http://www.bbc.co.uk/guidelines/futuremedia/accessibility/html/progressive-enhancement.shtml

It may be possible to emulate (fake) by preventing a pages JS files from loading or running, rather than switching off the javascript needed to test.

**Comment by andymsuk** [comment]
Is this still something we want to think about?

**Comment by greenc05** [comment]
I would certainly be interested to see a feature like this

**Comment by ermi-ltd** [comment]
+1 from me

**Comment by EmmaJP** [comment]
Keeping this as a future enhancement idea... simulating javascript disabled by somehow preventing page scripts from loading.

**Comment by Zlitus** [comment]
Chrome Puppeteer can stop javascript "on-the-go" via the «  setjavascriptenabled() » function. So I guess, Electron could do too? :-)

https://puppeteer.github.io/puppeteer/docs/puppeteer.page.setjavascriptenabled/
