### ISSUE TITLE
Linking to bug tickets

### ISSUE THREAD

**Issue by staylos92** [bbc/bbc-a11y#68]
It might be useful if it is possible to link to Jira tickets on any tests that we mark as 'Ignored' I fear that if we mark things as ignored due to known issues we will forget to un-ignore them once the related Jira ticket is closed.

**Comment by EmmaJP** [comment]
This was the key usefulness of differentiating between ignoring part the a web page that is not relevant to a development team, and temporarily ignoring a known fail until a fix can be implemented.  I still think it may be useful to either distinguish between these, or include some detail about ignored issues in the output (eg. Tests run: xxx  Passed: xx  Failed: 0  Ignored: xx)

**Comment by joshski** [comment]
Nice idea, thanks @staylos92. We'll factor this into our ignoring configuration.

**Comment by joshski** [comment]
I'm actually thinking that we should always ask for a reason for skipping standards, because it's so important to note why you're skipping them...

So maybe we could stop supporting this format:

```ruby
page "http://some/page.html" do
  skip_standard "some standard"
end
```

...and only support this instead:

```ruby
page "http://some/page.html" do
  skip_standard "some standard", reason: "the reason why we are skipping"
end
```

or something like that anyway

**Comment by EmmaJP** [comment]
Would that be tracked in some way?

**Comment by greenc05** [comment]
Sounds good @joshski When we have the browser interface, it would be good to see what/why things were being skipped, though only if you could save the output/skips for others to see. Though if people are just running these tests locally with a one time run - then I'm not sure the reason is needed (would just take longer to add the skips), unless it's stored somewhere or tracked like @EmmaJP says? Maybe useful on a nightly build?

**Comment by joshski** [comment]
I don't really know what you mean by tracking. So let's say you had a Jira ticket ABC123, then you could mention it in the reason:
```ruby
page "http://some/page.html" do
  skip_standard "Headings: exactly one main heading", reason: "JIRA ABC123"
end
```

...then running the tool you might see this kind of thing in the console output:
```bash
  * Skipped Headings: exactly one main heading, reason: JIRA ABC123
```

Now, when the ticket is closed then you'd probably want to stop skipping. Is that what you mean by tracking?

In this case you could easily write a script that found "JIRA xxxx" in the output and checked whether those JIRA tickets were closed. Or easier, if we had a [formatter API](https://github.com/bbc/bbc-a11y/issues/90) then you could use that to integrate with JIRA.

**Comment by EmmaJP** [comment]
Is any of this included in the current ability to skip tests or ignore results? And if so, is that in the documentation?

**Comment by andymsuk** [comment]
Now the config is in JS, it's really easy to add a comment. e.g.:

```js
page('http://www.bbc.co.uk', {
  skip: [
    'Headings: Content must follow headings', // Awaiting JIRA-1234
    'Minimum Text Size: Text cannot be too small'  // Awaiting JIRA-1235
  ]
})
page('http://www.bbc.co.uk/news', {
  skip: 'Headings: Content must follow headings' // Awaiting JIRA-1236
})

Given this, can we close this issue?

**Comment by staylos92** [comment]
Yeah, I think so 👍
