### ISSUE TITLE
Element visibility: which other standards are affected?

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#76]
I fixed one standards check because of CSS visibility: https://github.com/cucumber-ltd/bbc-a11y/pull/75

Which others need a tweak now?

**Comment by mattwynne** [comment]
Who would know? @EmmaJP perhaps?

**Comment by joshski** [comment]
These standards checks don't consider visibility, but it may be relevant:

* Anchors must have href attributes
* Forms must have submit buttons
* Fields must have labels or titles
* Content must follow headings
* Headings must be in ascending order
* Images must have alt attributes
* Exactly one main landmark
* Elements with zero tab index must be fields

If somebody can make the call on which ones should consider visibility, we can fix the checks pretty easily.

**Comment by EmmaJP** [comment]
Visibility is complex.  Some things may be hidden from sighted users but kept visible to a screen reader (eg. headings).  Some things may be hidden temporarily until a user interaction changes their state.  Some things may be hidden always and be only for things behind the scenes.

My best guesses and advise/comments:

- Anchors must have href attributes ... which standard is this associated with?  An anchor without an href is valid HTML, though not used so often now, and should probably be invisible through not having content.
- Forms must have submit buttons ... if they take user input. A hidden form may not take any input.  Or it may be temporarily hidden and later become visible, at which point the standard applies.
- Fields must have labels or titles ... this is input fields.  Same as above, it kind of depends why the form is hidden.
- Content must follow headings ... irrelevant of visibility. Lower level headings count as content.
- Headings must be in ascending order ... as above.
- Images must have alt attributes ... again, this would depend on why an image is being hidden. Unlike forms, I can't think of a good reason to hide an image that is not temporary, so I think check for an alt attribute irrelevant of visibility.
- Exactly one main landmark ... a page should have exactly one main landmark around the primary content.  This should not be hidden.
- Elements with zero tab index must be fields ... actually, they must not be elements that can receive focus by default, so I'm going to question this check.  As to visibility of elements with tab index zero, I think it would also depend on whether the element is hidden temporarily.  If hidden always, then it does not need to be in the tab order at all.
