### ISSUE TITLE
Minimum text size: don't report parent and child elements

### ISSUE THREAD

**Issue by mattwynne** [bbc/bbc-a11y#80]
When there's a minimum font size violation in an element, we report errors for all the parent elements right up to and including the body.

Instead, we only need to report the inner text element.

**Comment by EmmaJP** [comment]
Did this get fixed? This is the current result from BBC homepage test:

* Minimum Text Size: Text cannot be too small
    - Text size too small (2px): //h1[@id='hp-bbc-homepage-content']
    - Text size too small (10px): //div[@id='orb-modules']/div[2]/section[2]/div/div/p[1]
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[4]/div/div/div/div[3]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[9]/div[1]/div/div/div[1]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[11]/div[1]/div/div/div[3]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[14]/div[1]/div/div/div[1]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[14]/div[1]/div/div/div[2]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[16]/div/div/div/div[1]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[17]/div[1]/div/div/div[1]/a/div[1]/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[1]/button[1]/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[1]/button[2]/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[1]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[2]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[3]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[4]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[5]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[18]/div[1]/div/div[1]/div[2]/div/div/div/a[6]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[1]/button[1]/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[1]/button[2]/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[1]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[2]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[3]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[4]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[5]/div[1]/div/span/span
    - Text size too small (2px): //div[@id='orb-modules']/div[2]/section[19]/div[1]/div/div[1]/div[2]/div/div/div/a[6]/div[1]/div/span/span
    - Text size too small (10px): //div[@id='navp-orb-footer-promo']/div/div/div[1]/div/ul/li[1]/a/div/div/span/span
    - Text size too small (10px): //div[@id='navp-orb-footer-promo']/div/div/div[1]/div/ul/li[3]/a/div/div/span/span
    - Text size too small (10px): //div[@id='navp-orb-footer-promo']/div/div/div[1]/div/ul/li[4]/a/div/div/span/span
    - Text size too small (2px): //div[@id='navp-orb-footer-promo']/div/div/div[2]/button[1]/span
    - Text size too small (2px): //div[@id='navp-orb-footer-promo']/div/div/div[2]/button[2]/span

**Comment by joshski** [comment]
No, parent and child elements are reported, by design:

https://github.com/bbc/bbc-a11y/blob/master/features/check_standards/08_minimum_text_size.feature#L15

This is noisy, but actually I think the title of this issue is wrong. I think we want to ignore _child_ elements when both the parent and the child have text that is too small. So I'm changing the title.

**Comment by EmmaJP** [comment]
Cheers
