### ISSUE TITLE
Make chrome plugin easy to install

### ISSUE THREAD

**Issue by joshski** [bbc/bbc-a11y#88]
But not via the chrome store for now...

**Comment by joshski** [comment]
I think the electron implementation is better than the chrome plugin

**Comment by EmmaJP** [comment]
Is this because it can show a browser window?

**Comment by joshski** [comment]
We have much more control over how the electron window behaves.. With a chrome plugin it's difficult or impossible to perform some of the standards checks, e.g. for security reasons, so it seems that putting more effort into the chrome plugin is not worthwhile or sustainable. Our energy could be better spent making the electron implementation easier to install. So I'm closing this until somebody disagrees.

**Comment by EmmaJP** [comment]
Agree
