### ISSUE TITLE
Text size too small - Off-screen text fails

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#99]
On News and World Service websites we use the following CSS to hide text off-screen that describes media icons such as 'Video' etc.

```
position: absolute !important;
clip: rect(1px 1px 1px 1px);
clip: rect(1px, 1px, 1px, 1px);
padding: 0 !important;
border: 0 !important;
height: 1px !important;
width: 1px !important;
overflow: hidden;
```

No font-size is applied as this will never be seen. There is therefore no need to add a text size in this case and thus this fails the 'Text size too small' standard. It seems wrong to add a text size to the CSS for this just to make the test pass. Is there anything we can do about this @EmmaJP @joshski @mattwynne other than adding a needless font-size here?

<img width="1148" alt="screen shot 2016-02-03 at 16 02 13" src="https://cloud.githubusercontent.com/assets/1061401/12788184/804cc9cc-ca90-11e5-9b59-aab9571de7e6.png">

**Comment by EmmaJP** [comment]
This text shouldn't need a text size applied to it specifically, but it should be picking up a text size from a parent that would pass the tests.  For example, there should be a text size applied to the parent <a> or <li> tag that the <span> inherits.  This should not be overridden just because the text container is clipped and the overflow hidden.

**Comment by greenc05** [comment]
@EmmaJP The computed text size is 7.98px, in order for that to be something else I would have to define a needless font size else where for inheritence... We aren't defining font sizes on a's or li's as you can get into issues when you have multiple elements inside these, such as a badge and text that need to be different sizes, this way it becomes harder to control the sizing...

**Comment by EmmaJP** [comment]
How is the computed font size 7.98px when the html default font size is 10px?  Something else in the cascade must be changing the size that text inherits.  My suggestion is find that and change that.

**Comment by greenc05** [comment]
Thanks @EmmaJP I will take another look at it...

**Comment by joshski** [comment]
Closing this for now. As @EmmaJP points out, text is only too small if some CSS has made it too small.

Please open a new issue with a current example if it's still a problem.
